-- ════════════════════════════════════════════════════════════════════════════
-- MIGRATION: 20260605000002_phase4g_depreciation_engine.sql
-- Platform:  Trafikskolan SaaS — Swedish Driving School ERP
-- Phase:     4G — Depreciation Engine & Asset Posting Functions
--
-- Implements deterministic depreciation accounting:
--   • depreciation_schedules — predetermined schedule per asset (immutable once posted)
--   • BAS 7890: Nedskrivningar anläggningstillgångar (Impairment write-downs)
--
--   SECURITY DEFINER functions:
--   register_fixed_asset(...)          — registers asset + posts acquisition journal
--   generate_depreciation_schedule(...)— builds full predetermined schedule
--   post_depreciation_period(...)      — posts one period via post_journal_entry()
--   post_asset_disposal(...)           — disposal accounting (gain/loss journal)
--   post_impairment_adjustment(...)    — impairment write-down + schedule regeneration
--
--   Views:
--   v_fixed_asset_register            — asset register with class + NBV details
--   v_depreciation_schedule_summary   — schedule progress per asset
--
-- Voucher series 'D' (Anläggningstillgångar) used for all Phase 4G journal entries.
--
-- Depreciation balance proof (straight-line):
--   Per period: DR 7820 (depr_exp) / CR 1259 (acc_depr) = amount
--   Over life:  SUM(amount) = acquisition_cost - residual_value ✓
--
-- Disposal balance proof (example: sale at gain):
--   DR acc_depr + DR proceeds → CR asset_cost + CR gain
--   acc_depr + proceeds = cost + (proceeds - NBV) = cost + proceeds - (cost - acc_depr)
--   = acc_depr + proceeds ✓
--
-- Dependencies:
--   20260605000001_phase4g_fixed_assets.sql
--   20260602000002_phase4d_posting_engine.sql — post_journal_entry()
-- ════════════════════════════════════════════════════════════════════════════

-- ── BAS: Impairment write-down expense account ────────────────────────────────

INSERT INTO public.bas_account_catalog
  (account_code, account_name, account_name_en, account_type, normal_balance, sort_order)
VALUES
  ('7890', 'Nedskrivningar av anläggningstillgångar',
           'Impairment write-downs on fixed assets',           'expense',   'debit',  7890)
ON CONFLICT (account_code) DO NOTHING;

-- ── depreciation_schedules ───────────────────────────────────────────────────
-- Predetermined depreciation schedule per asset. Generated by
-- generate_depreciation_schedule(). Each row = one monthly period.
-- Once is_posted = true the row is immutable (trigger below).

CREATE TABLE public.depreciation_schedules (
  id                  uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  organization_id     uuid          NOT NULL REFERENCES public.organizations(id)  ON DELETE RESTRICT,
  asset_id            uuid          NOT NULL REFERENCES public.fixed_assets(id)   ON DELETE RESTRICT,
  period_number       int           NOT NULL CHECK (period_number >= 1),
  schedule_date       date          NOT NULL,   -- first day of the target month
  depreciation_amount numeric(14,2) NOT NULL CHECK (depreciation_amount >= 0),
  opening_nbv         numeric(14,2) NOT NULL CHECK (opening_nbv >= 0),
  closing_nbv         numeric(14,2) NOT NULL CHECK (closing_nbv >= 0),
  is_posted           boolean       NOT NULL DEFAULT false,
  posted_at           timestamptz,
  journal_entry_id    uuid                   REFERENCES public.journal_entries(id) ON DELETE RESTRICT,
  created_at          timestamptz   NOT NULL DEFAULT now(),

  CONSTRAINT ds_asset_period_unique UNIQUE (asset_id, period_number),
  CONSTRAINT ds_nbv_balance         CHECK (ABS(closing_nbv - (opening_nbv - depreciation_amount)) < 0.02)
);

COMMENT ON TABLE public.depreciation_schedules IS
  'Predetermined depreciation schedule per asset. Generated by generate_depreciation_schedule(). '
  'Each row represents one monthly posting. Once is_posted=true, immutable (trigger). '
  'Ledger-derived: amounts are computed from acquisition_cost and residual_value. '
  'Unposted lines can be regenerated after an impairment write-down.';
COMMENT ON COLUMN public.depreciation_schedules.schedule_date IS
  'First day of the month this depreciation entry applies to.';
COMMENT ON COLUMN public.depreciation_schedules.period_number IS
  'Sequential number starting at 1 for the first depreciation month.';

CREATE OR REPLACE FUNCTION public.prevent_posted_depreciation_mutation()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF OLD.is_posted THEN
    RAISE EXCEPTION
      'DEPRECIATION_SCHEDULE_IMMUTABLE: posted depreciation schedule lines cannot be modified or deleted. '
      'Use post_impairment_adjustment() to correct asset value, then call generate_depreciation_schedule() '
      'to regenerate the unposted portion.'
      USING ERRCODE = 'P0001';
  END IF;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION public.prevent_posted_depreciation_mutation() IS
  'BEFORE UPDATE OR DELETE guard on depreciation_schedules. Blocks mutation of posted lines.';

CREATE TRIGGER depreciation_schedules_immutability
  BEFORE UPDATE OR DELETE ON public.depreciation_schedules
  FOR EACH ROW EXECUTE FUNCTION public.prevent_posted_depreciation_mutation();

ALTER TABLE public.depreciation_schedules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "ds_org_read"
  ON public.depreciation_schedules FOR SELECT
  USING (
    organization_id = public.auth_organization_id()
    AND public.has_permission('finance:assets:read')
  );

GRANT SELECT                 ON public.depreciation_schedules TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.depreciation_schedules TO service_role;

-- ── FUNCTION: register_fixed_asset ───────────────────────────────────────────
-- Registers a new fixed asset and optionally posts the acquisition journal entry.
-- Transitions asset to 'active' immediately.
--
-- Acquisition journal (if p_period_id IS NOT NULL):
--   DR asset_class.asset_account (acquisition_cost)    — e.g. 1250 Inventarier
--   CR p_credit_account (default '2440')               — e.g. 2440 Leverantörsskulder
-- Voucher series 'D'.

CREATE OR REPLACE FUNCTION public.register_fixed_asset(
  p_org_id               uuid,
  p_period_id            uuid,
  p_asset_class_id       uuid,
  p_asset_code           text,
  p_asset_name           text,
  p_acquisition_date     date,
  p_acquisition_cost     numeric(14,2),
  p_residual_value       numeric(14,2)            DEFAULT 0,
  p_useful_life_months   int                      DEFAULT 60,
  p_depreciation_method  public.depreciation_method DEFAULT 'straight_line',
  p_credit_account       text                     DEFAULT '2440',
  p_description          text                     DEFAULT NULL,
  p_notes                text                     DEFAULT NULL,
  p_actor_id             uuid                     DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_asset_id  uuid;
  v_class     public.fixed_asset_classes%ROWTYPE;
  v_entry_id  uuid;
  v_lines     jsonb;
BEGIN
  SELECT * INTO v_class FROM public.fixed_asset_classes WHERE id = p_asset_class_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'ASSET_CLASS_NOT_FOUND: class % does not exist', p_asset_class_id
      USING ERRCODE = 'P0002';
  END IF;

  IF p_acquisition_cost <= 0 THEN
    RAISE EXCEPTION 'ASSET_INVALID_COST: acquisition_cost must be positive'
      USING ERRCODE = 'P0001';
  END IF;
  IF p_residual_value >= p_acquisition_cost THEN
    RAISE EXCEPTION 'ASSET_RESIDUAL_GEQ_COST: residual_value (%) must be less than acquisition_cost (%)',
      p_residual_value, p_acquisition_cost
      USING ERRCODE = 'P0001';
  END IF;

  -- Insert asset record directly as 'active'
  INSERT INTO public.fixed_assets
    (organization_id, asset_class_id, financial_period_id, asset_code, asset_name,
     description, acquisition_date, acquisition_cost, residual_value, useful_life_months,
     depreciation_method, status, net_book_value, accumulated_depreciation, periods_posted,
     notes, created_by)
  VALUES
    (p_org_id, p_asset_class_id, p_period_id, p_asset_code, p_asset_name,
     p_description, p_acquisition_date, p_acquisition_cost, p_residual_value, p_useful_life_months,
     p_depreciation_method, 'active', p_acquisition_cost, 0, 0,
     p_notes, p_actor_id)
  RETURNING id INTO v_asset_id;

  -- Post acquisition journal if period provided
  IF p_period_id IS NOT NULL THEN
    v_lines := jsonb_build_array(
      jsonb_build_object(
        'account_code',  v_class.asset_account,
        'debit_amount',  p_acquisition_cost,
        'credit_amount', 0,
        'description',   'Anskaffning: ' || p_asset_name
      ),
      jsonb_build_object(
        'account_code',  p_credit_account,
        'debit_amount',  0,
        'credit_amount', p_acquisition_cost,
        'description',   'Anskaffning: ' || p_asset_name
      )
    );

    v_entry_id := public.post_journal_entry(
      p_org_id,
      p_period_id,
      'standard'::public.journal_entry_type,
      p_acquisition_date,
      'Anskaffning anläggningstillgång: ' || p_asset_name,
      v_lines,
      'FixedAsset.Acquired',
      'fixed_asset',
      v_asset_id,
      'D',
      NULL, NULL,
      p_actor_id
    );

    UPDATE public.fixed_assets
    SET acquisition_entry_id = v_entry_id
    WHERE id = v_asset_id;
  END IF;

  RETURN v_asset_id;
END;
$$;

COMMENT ON FUNCTION public.register_fixed_asset(uuid,uuid,uuid,text,text,date,numeric,numeric,int,public.depreciation_method,text,text,text,uuid) IS
  'Registers a new fixed asset, immediately activates it, and optionally posts the '
  'acquisition journal (DR asset_account / CR p_credit_account, default 2440). '
  'Returns the asset id.';

GRANT EXECUTE ON FUNCTION public.register_fixed_asset(uuid,uuid,uuid,text,text,date,numeric,numeric,int,public.depreciation_method,text,text,text,uuid) TO service_role;

-- ── FUNCTION: generate_depreciation_schedule ────────────────────────────────
-- Generates the full predetermined depreciation schedule for an asset.
-- Idempotent: deletes existing unposted lines before regenerating.
-- Starts from (periods_posted + 1) at current net_book_value.
-- Returns count of schedule lines generated.

CREATE OR REPLACE FUNCTION public.generate_depreciation_schedule(
  p_asset_id uuid,
  p_actor_id uuid DEFAULT NULL
)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_asset          public.fixed_assets%ROWTYPE;
  v_period_amount  numeric(14,2);
  v_opening_nbv    numeric(14,2);
  v_closing_nbv    numeric(14,2);
  v_schedule_date  date;
  v_start_period   int;
  v_count          int := 0;
  i                int;
BEGIN
  SELECT * INTO v_asset FROM public.fixed_assets WHERE id = p_asset_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'ASSET_NOT_FOUND: asset % does not exist', p_asset_id
      USING ERRCODE = 'P0002';
  END IF;

  IF v_asset.status = 'disposed' THEN
    RAISE EXCEPTION 'ASSET_DISPOSED: cannot generate schedule for a disposed asset'
      USING ERRCODE = 'P0001';
  END IF;

  IF v_asset.depreciation_method = 'none' THEN
    RETURN 0;
  END IF;

  -- Delete unposted lines (allows idempotent regeneration and post-impairment regeneration)
  DELETE FROM public.depreciation_schedules
  WHERE  asset_id  = p_asset_id
    AND  is_posted = false;

  v_start_period  := v_asset.periods_posted + 1;
  v_opening_nbv   := v_asset.net_book_value;

  -- First unposted schedule_date: month after acquisition + already-posted months
  v_schedule_date := (
    date_trunc('month', v_asset.acquisition_date + interval '1 month')
    + (v_asset.periods_posted * interval '1 month')
  )::date;

  -- Straight-line: constant amount per period
  IF v_asset.depreciation_method = 'straight_line' THEN
    v_period_amount := ROUND(
      (v_asset.acquisition_cost - v_asset.residual_value) / v_asset.useful_life_months, 2
    );
  END IF;

  i := v_start_period;

  WHILE i <= v_asset.useful_life_months AND v_opening_nbv > v_asset.residual_value LOOP
    -- Declining balance: recalculate each period on current NBV
    IF v_asset.depreciation_method = 'declining_balance' THEN
      v_period_amount := ROUND(
        v_opening_nbv * 2.0 / v_asset.useful_life_months, 2
      );
    END IF;

    -- Clamp: do not depreciate below residual value
    v_period_amount := LEAST(v_period_amount, v_opening_nbv - v_asset.residual_value);

    -- Final period: absorb accumulated rounding to reach exactly residual_value
    IF i = v_asset.useful_life_months OR
       (v_opening_nbv - v_period_amount) < (v_asset.residual_value + 0.01) THEN
      v_period_amount := v_opening_nbv - v_asset.residual_value;
    END IF;

    v_closing_nbv := v_opening_nbv - v_period_amount;

    INSERT INTO public.depreciation_schedules
      (organization_id, asset_id, period_number, schedule_date,
       depreciation_amount, opening_nbv, closing_nbv)
    VALUES
      (v_asset.organization_id, p_asset_id, i, v_schedule_date,
       v_period_amount, v_opening_nbv, v_closing_nbv);

    v_opening_nbv   := v_closing_nbv;
    v_schedule_date := (v_schedule_date + interval '1 month')::date;
    i               := i + 1;
    v_count         := v_count + 1;
  END LOOP;

  RETURN v_count;
END;
$$;

COMMENT ON FUNCTION public.generate_depreciation_schedule(uuid, uuid) IS
  'Generates the full predetermined depreciation schedule for an asset. '
  'Deletes unposted lines first (idempotent). '
  'Supports straight_line and declining_balance methods. '
  'Final-period rounding absorbed to reach exactly residual_value. '
  'Returns count of schedule lines created.';

GRANT EXECUTE ON FUNCTION public.generate_depreciation_schedule(uuid, uuid) TO service_role;

-- ── FUNCTION: post_depreciation_period ───────────────────────────────────────
-- Posts the next pending depreciation period for an asset.
-- Uses the lowest period_number unposted line from depreciation_schedules.
-- Returns the journal entry id.

CREATE OR REPLACE FUNCTION public.post_depreciation_period(
  p_asset_id  uuid,
  p_period_id uuid,
  p_actor_id  uuid DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_asset     public.fixed_assets%ROWTYPE;
  v_class     public.fixed_asset_classes%ROWTYPE;
  v_schedule  public.depreciation_schedules%ROWTYPE;
  v_entry_id  uuid;
  v_lines     jsonb;
BEGIN
  SELECT * INTO v_asset FROM public.fixed_assets WHERE id = p_asset_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'ASSET_NOT_FOUND: asset % does not exist', p_asset_id
      USING ERRCODE = 'P0002';
  END IF;

  IF v_asset.status NOT IN ('active', 'impaired') THEN
    RAISE EXCEPTION
      'ASSET_NOT_DEPRECIABLE: asset status is %. Only active or impaired assets can be depreciated.',
      v_asset.status
      USING ERRCODE = 'P0001';
  END IF;

  SELECT * INTO v_class FROM public.fixed_asset_classes WHERE id = v_asset.asset_class_id;

  SELECT * INTO v_schedule
  FROM   public.depreciation_schedules
  WHERE  asset_id  = p_asset_id
    AND  is_posted = false
  ORDER  BY period_number ASC
  LIMIT  1;

  IF NOT FOUND THEN
    RAISE EXCEPTION
      'NO_DEPRECIATION_DUE: no unposted depreciation schedule line for asset %', p_asset_id
      USING ERRCODE = 'P0001';
  END IF;

  -- DR depreciation_exp_account / CR accumulated_depr_account
  v_lines := jsonb_build_array(
    jsonb_build_object(
      'account_code',  v_class.depreciation_exp_account,
      'debit_amount',  v_schedule.depreciation_amount,
      'credit_amount', 0,
      'description',
        'Avskrivning: ' || v_asset.asset_name
        || ' (' || v_schedule.period_number || '/' || v_asset.useful_life_months || ')'
    ),
    jsonb_build_object(
      'account_code',  v_class.accumulated_depr_account,
      'debit_amount',  0,
      'credit_amount', v_schedule.depreciation_amount,
      'description',   v_asset.asset_name || ' ackumulerade avskrivningar'
    )
  );

  v_entry_id := public.post_journal_entry(
    v_asset.organization_id,
    p_period_id,
    'standard'::public.journal_entry_type,
    v_schedule.schedule_date,
    'Avskrivning ' || v_asset.asset_name
      || ' period ' || v_schedule.period_number || '/' || v_asset.useful_life_months,
    v_lines,
    'FixedAsset.Depreciated',
    'fixed_asset',
    p_asset_id,
    'D',
    NULL, NULL,
    p_actor_id
  );

  -- Mark line posted
  UPDATE public.depreciation_schedules
  SET is_posted = true, posted_at = now(), journal_entry_id = v_entry_id
  WHERE id = v_schedule.id;

  -- Update asset running totals
  UPDATE public.fixed_assets
  SET accumulated_depreciation = accumulated_depreciation + v_schedule.depreciation_amount,
      net_book_value            = net_book_value - v_schedule.depreciation_amount,
      periods_posted            = periods_posted + 1,
      last_depreciation_date    = v_schedule.schedule_date,
      status = CASE
        WHEN (net_book_value - v_schedule.depreciation_amount) <= residual_value + 0.01
        THEN 'fully_depreciated'::public.fixed_asset_status
        ELSE status
      END,
      fully_depreciated_at = CASE
        WHEN (net_book_value - v_schedule.depreciation_amount) <= residual_value + 0.01
          AND fully_depreciated_at IS NULL
        THEN v_schedule.schedule_date
        ELSE fully_depreciated_at
      END,
      updated_by = p_actor_id,
      updated_at = now()
  WHERE id = p_asset_id;

  RETURN v_entry_id;
END;
$$;

COMMENT ON FUNCTION public.post_depreciation_period(uuid, uuid, uuid) IS
  'Posts the next pending depreciation period for an asset. '
  'Selects the lowest unposted period_number from depreciation_schedules. '
  'Journal: DR depreciation_exp_account / CR accumulated_depr_account. '
  'Updates asset.net_book_value, accumulated_depreciation, periods_posted. '
  'Transitions asset to fully_depreciated when NBV reaches residual_value.';

GRANT EXECUTE ON FUNCTION public.post_depreciation_period(uuid, uuid, uuid) TO service_role;

-- ── FUNCTION: post_asset_disposal ────────────────────────────────────────────
-- Records asset disposal and posts the disposal journal entry.
-- Returns the asset_disposals.id.
--
-- Journal entries:
--   Always: DR acc_depr_account (accumulated_depreciation)
--           CR asset_account    (acquisition_cost)
--   If proceeds > 0: DR 1930 Bank (proceeds)
--   If gain (proceeds > NBV):  CR gain_account (gain_loss)
--   If loss (proceeds < NBV):  DR loss_account (ABS(gain_loss))
--   Balance proof: DR = CR in all cases (verified above in header comment).

CREATE OR REPLACE FUNCTION public.post_asset_disposal(
  p_asset_id      uuid,
  p_period_id     uuid,
  p_disposal_type public.asset_disposal_type,
  p_disposal_date date,
  p_proceeds      numeric(14,2) DEFAULT 0,
  p_notes         text          DEFAULT NULL,
  p_actor_id      uuid          DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_asset       public.fixed_assets%ROWTYPE;
  v_class       public.fixed_asset_classes%ROWTYPE;
  v_gain_loss   numeric(14,2);
  v_lines       jsonb;
  v_entry_id    uuid;
  v_disposal_id uuid;
BEGIN
  SELECT * INTO v_asset FROM public.fixed_assets WHERE id = p_asset_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'ASSET_NOT_FOUND' USING ERRCODE = 'P0002';
  END IF;
  IF v_asset.status = 'disposed' THEN
    RAISE EXCEPTION 'ASSET_ALREADY_DISPOSED: asset % is already disposed', p_asset_id
      USING ERRCODE = 'P0001';
  END IF;
  IF v_asset.status = 'draft' THEN
    RAISE EXCEPTION 'ASSET_DRAFT: cannot dispose a draft asset'
      USING ERRCODE = 'P0001';
  END IF;
  IF p_proceeds < 0 THEN
    RAISE EXCEPTION 'DISPOSAL_NEGATIVE_PROCEEDS: proceeds must be >= 0'
      USING ERRCODE = 'P0001';
  END IF;

  SELECT * INTO v_class FROM public.fixed_asset_classes WHERE id = v_asset.asset_class_id;

  v_gain_loss := p_proceeds - v_asset.net_book_value;

  -- Build journal lines array
  v_lines := jsonb_build_array(
    -- Remove accumulated depreciation (debit contra-asset to zero it out)
    jsonb_build_object(
      'account_code',  v_class.accumulated_depr_account,
      'debit_amount',  v_asset.accumulated_depreciation,
      'credit_amount', 0,
      'description',   'Avyttring ackumulerade avskrivningar: ' || v_asset.asset_name
    ),
    -- Remove acquisition cost
    jsonb_build_object(
      'account_code',  v_class.asset_account,
      'debit_amount',  0,
      'credit_amount', v_asset.acquisition_cost,
      'description',   'Avyttring anskaffningsvärde: ' || v_asset.asset_name
    )
  );

  -- Book cash proceeds if any
  IF p_proceeds > 0 THEN
    v_lines := v_lines || jsonb_build_array(
      jsonb_build_object(
        'account_code',  '1930',
        'debit_amount',  p_proceeds,
        'credit_amount', 0,
        'description',   'Avyttring likvid: ' || v_asset.asset_name
      )
    );
  END IF;

  -- Book gain or loss
  IF v_gain_loss > 0 THEN
    v_lines := v_lines || jsonb_build_array(
      jsonb_build_object(
        'account_code',  v_class.disposal_gain_account,
        'debit_amount',  0,
        'credit_amount', v_gain_loss,
        'description',   'Realisationsvinst: ' || v_asset.asset_name
      )
    );
  ELSIF v_gain_loss < 0 THEN
    v_lines := v_lines || jsonb_build_array(
      jsonb_build_object(
        'account_code',  v_class.disposal_loss_account,
        'debit_amount',  ABS(v_gain_loss),
        'credit_amount', 0,
        'description',   'Realisationsförlust: ' || v_asset.asset_name
      )
    );
  END IF;

  v_entry_id := public.post_journal_entry(
    v_asset.organization_id,
    p_period_id,
    'standard'::public.journal_entry_type,
    p_disposal_date,
    'Avyttring anläggningstillgång: ' || v_asset.asset_name,
    v_lines,
    'FixedAsset.Disposed',
    'fixed_asset',
    p_asset_id,
    'D',
    NULL, NULL,
    p_actor_id
  );

  INSERT INTO public.asset_disposals
    (organization_id, asset_id, disposal_type, disposal_date,
     net_book_value_at_disposal, proceeds, gain_loss, journal_entry_id, notes, created_by)
  VALUES
    (v_asset.organization_id, p_asset_id, p_disposal_type, p_disposal_date,
     v_asset.net_book_value, p_proceeds, v_gain_loss, v_entry_id, p_notes, p_actor_id)
  RETURNING id INTO v_disposal_id;

  UPDATE public.fixed_assets
  SET status          = 'disposed',
      disposal_id     = v_disposal_id,
      net_book_value  = 0,
      updated_by      = p_actor_id,
      updated_at      = now()
  WHERE id = p_asset_id;

  RETURN v_disposal_id;
END;
$$;

COMMENT ON FUNCTION public.post_asset_disposal(uuid, uuid, public.asset_disposal_type, date, numeric, text, uuid) IS
  'Records fixed asset disposal and posts the disposal journal entry. '
  'Journal: DR acc_depr / (DR bank if proceeds) / (DR loss or CR gain) / CR asset_cost. '
  'Creates immutable asset_disposals record. Sets asset.status = ''disposed''.';

GRANT EXECUTE ON FUNCTION public.post_asset_disposal(uuid, uuid, public.asset_disposal_type, date, numeric, text, uuid) TO service_role;

-- ── FUNCTION: post_impairment_adjustment ─────────────────────────────────────
-- Posts an impairment write-down for an active or impaired asset.
-- Reduces net_book_value and regenerates the unposted depreciation schedule.
-- Journal: DR 7890 Nedskrivningar / CR accumulated_depr_account.

CREATE OR REPLACE FUNCTION public.post_impairment_adjustment(
  p_asset_id          uuid,
  p_period_id         uuid,
  p_impairment_date   date,
  p_impairment_amount numeric(14,2),
  p_reason            text DEFAULT NULL,
  p_actor_id          uuid DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_asset    public.fixed_assets%ROWTYPE;
  v_class    public.fixed_asset_classes%ROWTYPE;
  v_lines    jsonb;
  v_entry_id uuid;
BEGIN
  SELECT * INTO v_asset FROM public.fixed_assets WHERE id = p_asset_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'ASSET_NOT_FOUND' USING ERRCODE = 'P0002';
  END IF;

  IF v_asset.status NOT IN ('active', 'impaired') THEN
    RAISE EXCEPTION
      'ASSET_NOT_IMPAIRMENT_ELIGIBLE: status is %, must be active or impaired',
      v_asset.status
      USING ERRCODE = 'P0001';
  END IF;

  IF p_impairment_amount <= 0 THEN
    RAISE EXCEPTION 'IMPAIRMENT_INVALID_AMOUNT: impairment amount must be positive'
      USING ERRCODE = 'P0001';
  END IF;

  IF p_impairment_amount > (v_asset.net_book_value - v_asset.residual_value) THEN
    RAISE EXCEPTION
      'IMPAIRMENT_EXCEEDS_DEPRECIABLE_NBV: amount (%) exceeds depreciable NBV (%)',
      p_impairment_amount, (v_asset.net_book_value - v_asset.residual_value)
      USING ERRCODE = 'P0001';
  END IF;

  SELECT * INTO v_class FROM public.fixed_asset_classes WHERE id = v_asset.asset_class_id;

  v_lines := jsonb_build_array(
    jsonb_build_object(
      'account_code',  '7890',
      'debit_amount',  p_impairment_amount,
      'credit_amount', 0,
      'description',
        'Nedskrivning: ' || v_asset.asset_name
        || COALESCE(' — ' || p_reason, '')
    ),
    jsonb_build_object(
      'account_code',  v_class.accumulated_depr_account,
      'debit_amount',  0,
      'credit_amount', p_impairment_amount,
      'description',   v_asset.asset_name || ' nedskrivning'
    )
  );

  v_entry_id := public.post_journal_entry(
    v_asset.organization_id,
    p_period_id,
    'standard'::public.journal_entry_type,
    p_impairment_date,
    'Nedskrivning anläggningstillgång: ' || v_asset.asset_name,
    v_lines,
    'FixedAsset.Impaired',
    'fixed_asset',
    p_asset_id,
    'D',
    NULL, NULL,
    p_actor_id
  );

  UPDATE public.fixed_assets
  SET accumulated_depreciation  = accumulated_depreciation + p_impairment_amount,
      net_book_value             = net_book_value - p_impairment_amount,
      status                     = 'impaired',
      updated_by                 = p_actor_id,
      updated_at                 = now()
  WHERE id = p_asset_id;

  -- Regenerate unposted schedule from new (lower) NBV
  PERFORM public.generate_depreciation_schedule(p_asset_id, p_actor_id);

  RETURN v_entry_id;
END;
$$;

COMMENT ON FUNCTION public.post_impairment_adjustment(uuid, uuid, date, numeric, text, uuid) IS
  'Posts an impairment write-down: DR 7890 Nedskrivningar / CR accumulated_depr_account. '
  'Updates asset.net_book_value and status → ''impaired''. '
  'Regenerates unposted depreciation schedule from the reduced NBV.';

GRANT EXECUTE ON FUNCTION public.post_impairment_adjustment(uuid, uuid, date, numeric, text, uuid) TO service_role;

-- ── Views ──────────────────────────────────────────────────────────────────────

CREATE VIEW public.v_fixed_asset_register
WITH (security_invoker = true)
AS
SELECT
  fa.id,
  fa.organization_id,
  fa.asset_code,
  fa.asset_name,
  fa.description,
  fac.class_code,
  fac.class_name,
  fac.class_name_en,
  fa.depreciation_method,
  fa.acquisition_date,
  fa.acquisition_cost,
  fa.residual_value,
  (fa.acquisition_cost - fa.residual_value)   AS depreciable_amount,
  fa.useful_life_months,
  fa.accumulated_depreciation,
  fa.net_book_value,
  fa.periods_posted,
  (fa.useful_life_months - fa.periods_posted)  AS periods_remaining,
  fa.status,
  fa.last_depreciation_date,
  fa.fully_depreciated_at,
  fa.notes,
  fa.created_at,
  fa.updated_at,
  fac.asset_account,
  fac.accumulated_depr_account,
  fac.depreciation_exp_account
FROM  public.fixed_assets fa
JOIN  public.fixed_asset_classes fac ON fac.id = fa.asset_class_id;

COMMENT ON VIEW public.v_fixed_asset_register IS
  'Fixed asset register with class details and current net book values. '
  'security_invoker = true: each caller sees only their org''s assets.';

GRANT SELECT ON public.v_fixed_asset_register TO authenticated, service_role;

CREATE VIEW public.v_depreciation_schedule_summary
WITH (security_invoker = true)
AS
SELECT
  fa.id                                                        AS asset_id,
  fa.organization_id,
  fa.asset_code,
  fa.asset_name,
  fa.status                                                    AS asset_status,
  fa.acquisition_cost,
  fa.residual_value,
  COUNT(ds.id)                                                 AS total_periods,
  COUNT(ds.id) FILTER (WHERE ds.is_posted)                    AS posted_periods,
  COUNT(ds.id) FILTER (WHERE NOT ds.is_posted)                AS remaining_periods,
  MIN(ds.schedule_date) FILTER (WHERE NOT ds.is_posted)       AS next_depreciation_date,
  SUM(ds.depreciation_amount) FILTER (WHERE NOT ds.is_posted) AS remaining_depreciation,
  SUM(ds.depreciation_amount)                                  AS total_scheduled_depreciation
FROM  public.fixed_assets fa
LEFT  JOIN public.depreciation_schedules ds ON ds.asset_id = fa.id
GROUP BY fa.id, fa.organization_id, fa.asset_code, fa.asset_name,
         fa.status, fa.acquisition_cost, fa.residual_value;

COMMENT ON VIEW public.v_depreciation_schedule_summary IS
  'Depreciation schedule progress per asset. '
  'Shows posted vs remaining periods and next depreciation date. '
  'security_invoker = true.';

GRANT SELECT ON public.v_depreciation_schedule_summary TO authenticated, service_role;
