-- ════════════════════════════════════════════════════════════════════════════
-- MIGRATION: 20260602000005_phase4d_sie4_ledger_alignment.sql
-- Platform:  Trafikskolan SaaS — Swedish Driving School ERP
-- Phase:     4D — SIE4 Ledger Alignment and Financial Reports
--
-- Makes the journal ledger the authoritative source for SIE4 exports and
-- financial reports. Implements Swedish accounting report views and the
-- ledger-based SIE4 generation function.
--
-- New table:
--   ledger_sie4_exports  — immutable SIE4 exports generated from the journal ledger
--
-- Views (security_invoker):
--   v_trial_balance     — account balances per period: opening/movements/closing
--   v_income_statement  — revenue and expense accounts (resultaträkning)
--   v_balance_sheet     — asset, liability, equity accounts (balansräkning)
--
-- Function:
--   generate_sie4_from_ledger(p_org_id, p_period_id, p_actor_id)
--     → Generates a complete SIE4 file from the journal ledger for a period.
--       Uses journal_entries + journal_lines as the authoritative source.
--       Includes: #FILTYP, #FORMAT, #GEN, #SIETYP, #FNAMN, #ORGNR, #MOMSNR,
--                 #KPTYP BAS2020, #RAR, #KONTO, #IB, #UB, #VER/#TRANS blocks.
--       SHA-256 hashes the content for integrity verification.
--       Idempotent: returns existing export_id if already generated for this period.
--
-- SIE4 invariants:
--   #VER line per journal entry (voucher_series + voucher_number + date)
--   #TRANS per journal line: positive = debit, negative = credit
--   #IB / #UB from account_balances (opening/closing per period)
--   #KONTO for every account referenced in the period's entries
--   #GEN = today's date (generation date)
--   #RAR 0 = fiscal year dates from the financial_period
--   SHA-256 hash stored in ledger_sie4_exports.content_hash
--
-- Dependencies:
--   20260602000001_phase4d_ledger_core.sql
--   20260602000002_phase4d_posting_engine.sql
--   20260601000001_phase4c_swedish_finance_foundation.sql — bas_account_catalog
--   20260601000003_phase4c_invoice_compliance.sql         — organization_swedish_settings
--   20260604000004_phase4c_sie4_exports.sql               — prevent_sie4_export_mutation()
-- ════════════════════════════════════════════════════════════════════════════

-- ── Section 1: ledger_sie4_exports ───────────────────────────────────────────
-- Immutable SIE4 exports generated from the journal ledger.
-- One export per organization per financial_period (unique constraint).
-- content_hash enables reproducibility verification.

CREATE TABLE public.ledger_sie4_exports (
  id               uuid          NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  organization_id  uuid          NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
  financial_period_id uuid       NOT NULL REFERENCES public.financial_periods(id) ON DELETE RESTRICT,
  from_date        date          NOT NULL,
  to_date          date          NOT NULL,
  content_text     text          NOT NULL,
  content_hash     text          NOT NULL CHECK (length(content_hash) = 64),
  entry_count      int           NOT NULL DEFAULT 0 CHECK (entry_count >= 0),
  account_count    int           NOT NULL DEFAULT 0 CHECK (account_count >= 0),
  generated_at     timestamptz   NOT NULL DEFAULT now(),
  generated_by     uuid          REFERENCES auth.users(id) ON DELETE SET NULL,
  metadata         jsonb         NOT NULL DEFAULT '{}',

  CONSTRAINT lse_dates_check    CHECK (to_date >= from_date),
  CONSTRAINT lse_period_unique  UNIQUE (organization_id, financial_period_id)
);

COMMENT ON TABLE public.ledger_sie4_exports IS
  'Immutable SIE4 exports generated from the journal ledger. '
  'Each export covers one financial_period. SHA-256 hash enables reproducibility checks. '
  'Generated by generate_sie4_from_ledger(). Cannot be modified after creation.';

CREATE OR REPLACE FUNCTION public.prevent_ledger_sie4_mutation()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  RAISE EXCEPTION 'LEDGER_SIE4_IMMUTABLE: ledger SIE4 exports are permanent records. '
    'Generate a new export to replace a previous one (requires period re-open).'
    USING ERRCODE = 'P0001';
END;
$$;

CREATE TRIGGER ledger_sie4_exports_immutability
  BEFORE UPDATE OR DELETE ON public.ledger_sie4_exports
  FOR EACH ROW EXECUTE FUNCTION public.prevent_ledger_sie4_mutation();

-- ── Section 2: RLS ────────────────────────────────────────────────────────────

ALTER TABLE public.ledger_sie4_exports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "lse_org_read"
  ON public.ledger_sie4_exports FOR SELECT
  USING (
    organization_id = public.auth_organization_id()
    AND public.has_permission('finance:ledger:export')
  );

GRANT SELECT         ON public.ledger_sie4_exports TO authenticated;
GRANT SELECT, INSERT ON public.ledger_sie4_exports TO service_role;

-- ── Section 3: v_trial_balance ────────────────────────────────────────────────
-- Shows opening balance, period movements, and closing balance per account.
-- Joins with bas_account_catalog for account names and normal_balance.

CREATE VIEW public.v_trial_balance
WITH (security_invoker = true)
AS
SELECT
  ab.organization_id,
  ab.financial_period_id,
  fp.name                                              AS period_name,
  fp.period_start,
  fp.period_end,
  fp.status                                            AS period_status,
  ab.account_code,
  COALESCE(bac.account_name,    ab.account_code)       AS account_name,
  COALESCE(bac.account_name_en, ab.account_code)       AS account_name_en,
  COALESCE(bac.account_type,    'unknown')             AS account_type,
  COALESCE(bac.normal_balance,  'debit')               AS normal_balance,
  ab.opening_balance,
  ab.debit_movement,
  ab.credit_movement,
  ab.closing_balance,
  ab.transaction_count,
  ab.last_entry_id,
  ab.updated_at
FROM public.account_balances ab
JOIN public.financial_periods fp
  ON fp.id = ab.financial_period_id
LEFT JOIN public.bas_account_catalog bac
  ON bac.account_code = ab.account_code;

COMMENT ON VIEW public.v_trial_balance IS
  'Trial balance per (org, period, account). '
  'closing_balance = opening + debits − credits. '
  'For debit-normal accounts: positive = asset/expense balance. '
  'For credit-normal accounts: negative = liability/revenue balance.';

-- ── Section 4: v_income_statement (resultaträkning) ──────────────────────────
-- Revenue and expense accounts for the period.
-- Net income = sum(revenue credit movements) - sum(expense debit movements)

CREATE VIEW public.v_income_statement
WITH (security_invoker = true)
AS
SELECT
  tb.organization_id,
  tb.financial_period_id,
  tb.period_name,
  tb.period_start,
  tb.period_end,
  tb.account_code,
  tb.account_name,
  tb.account_type,
  tb.normal_balance,
  tb.debit_movement,
  tb.credit_movement,
  -- For revenue (credit-normal): net income contribution = credit - debit
  -- For expense (debit-normal):  net income contribution = -(debit - credit)
  CASE tb.account_type
    WHEN 'revenue' THEN tb.credit_movement - tb.debit_movement
    WHEN 'expense' THEN -(tb.debit_movement - tb.credit_movement)
    ELSE                0
  END AS net_contribution
FROM public.v_trial_balance tb
WHERE tb.account_type IN ('revenue', 'expense');

COMMENT ON VIEW public.v_income_statement IS
  'Income statement (resultaträkning) per period. '
  'net_contribution > 0 = profit contribution. '
  'Total net income = SUM(net_contribution) across all rows for a period.';

-- ── Section 5: v_balance_sheet (balansräkning) ───────────────────────────────
-- Asset, liability, and equity accounts as of the end of a period.

CREATE VIEW public.v_balance_sheet
WITH (security_invoker = true)
AS
SELECT
  tb.organization_id,
  tb.financial_period_id,
  tb.period_name,
  tb.period_end,
  tb.account_code,
  tb.account_name,
  tb.account_type,
  tb.normal_balance,
  tb.closing_balance,
  -- Reported balance: absolute value; sign is in normal_balance + closing_balance sign
  ABS(tb.closing_balance) AS reported_balance,
  -- Balance side: is this balance on the expected side?
  CASE
    WHEN tb.normal_balance = 'debit'  AND tb.closing_balance >= 0 THEN 'normal'
    WHEN tb.normal_balance = 'credit' AND tb.closing_balance <= 0 THEN 'normal'
    ELSE 'contra'
  END AS balance_position
FROM public.v_trial_balance tb
WHERE tb.account_type IN ('asset', 'liability', 'equity');

COMMENT ON VIEW public.v_balance_sheet IS
  'Balance sheet (balansräkning) accounts at period end. '
  'Assets have debit normal_balance (positive closing = debit balance). '
  'Liabilities/equity have credit normal_balance (negative closing = credit balance). '
  'balance_position = ''contra'' indicates an unusual contra balance.';

-- ── Section 6: generate_sie4_from_ledger ─────────────────────────────────────
-- Generates a complete SIE4 file from the journal ledger for a financial period.
-- Uses journal_entries + journal_lines as the authoritative source.
-- Stores the result in ledger_sie4_exports (immutable).
-- Idempotent: returns existing export_id if already generated for this period.

CREATE OR REPLACE FUNCTION public.generate_sie4_from_ledger(
  p_org_id    uuid,
  p_period_id uuid,
  p_actor_id  uuid DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_export_id      uuid;
  v_period         financial_periods%ROWTYPE;
  v_swedish        organization_swedish_settings%ROWTYPE;
  v_org            organizations%ROWTYPE;
  v_content        text;
  v_hash           text;
  v_entry_count    int  := 0;
  v_account_count  int  := 0;
  v_gen_date       text;
  v_entry          record;
  v_line           record;
  v_account        record;
  v_ib             record;
  v_ub             record;
BEGIN
  -- 1. Idempotency check
  SELECT id INTO v_export_id
  FROM   ledger_sie4_exports
  WHERE  organization_id    = p_org_id
    AND  financial_period_id = p_period_id;

  IF FOUND THEN
    RETURN v_export_id;
  END IF;

  -- 2. Fetch org and period
  SELECT * INTO v_org    FROM organizations    WHERE id = p_org_id;
  SELECT * INTO v_period FROM financial_periods WHERE id = p_period_id AND organization_id = p_org_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'PERIOD_NOT_FOUND: period % not found for org %', p_period_id, p_org_id
      USING ERRCODE = 'P0001';
  END IF;

  -- 3. Fetch Swedish settings (may not exist for all orgs)
  SELECT * INTO v_swedish
  FROM   organization_swedish_settings
  WHERE  organization_id = p_org_id;

  v_gen_date := TO_CHAR(CURRENT_DATE, 'YYYYMMDD');

  -- 4. Build SIE4 header
  v_content := '#FILTYP SIE4' || E'\n'
    || '#FORMAT PC8' || E'\n'
    || '#GEN ' || v_gen_date || E'\n'
    || '#SIETYP 4' || E'\n'
    || '#PROGRAM "Trafikskolan ERP" "4.0"' || E'\n'
    || '#FNAMN "' || COALESCE(v_swedish.sie4_company_name, v_org.legal_name, v_org.name) || '"' || E'\n'
    || '#ORGNR ' || COALESCE(v_swedish.org_number, '000000-0000') || E'\n';

  IF v_swedish.vat_reg_number IS NOT NULL THEN
    v_content := v_content || '#MOMSNR ' || v_swedish.vat_reg_number || E'\n';
  END IF;

  v_content := v_content
    || '#KPTYP BAS2020' || E'\n'
    || '#RAR 0 ' || TO_CHAR(v_period.period_start, 'YYYYMMDD')
               || ' ' || TO_CHAR(v_period.period_end, 'YYYYMMDD') || E'\n'
    || E'\n';

  -- 5. #KONTO — account catalog for all accounts used in this period
  FOR v_account IN
    SELECT DISTINCT
      jl.account_code,
      COALESCE(bac.account_name, jl.account_code) AS account_name
    FROM   journal_lines  jl
    JOIN   journal_entries je ON je.id = jl.entry_id
    LEFT   JOIN bas_account_catalog bac ON bac.account_code = jl.account_code
    WHERE  je.organization_id    = p_org_id
      AND  je.financial_period_id = p_period_id
      AND  je.status             = 'posted'
    ORDER  BY jl.account_code
  LOOP
    v_content := v_content
      || '#KONTO ' || v_account.account_code
      || ' "' || REPLACE(v_account.account_name, '"', '''') || '"'
      || E'\n';
    v_account_count := v_account_count + 1;
  END LOOP;

  v_content := v_content || E'\n';

  -- 6. #IB — opening balances from account_balances
  FOR v_ib IN
    SELECT account_code, opening_balance
    FROM   account_balances
    WHERE  organization_id    = p_org_id
      AND  financial_period_id = p_period_id
      AND  opening_balance   <> 0
    ORDER  BY account_code
  LOOP
    v_content := v_content
      || '#IB 0 ' || v_ib.account_code
      || ' ' || TO_CHAR(v_ib.opening_balance, 'FM999999999990.00')
      || E'\n';
  END LOOP;

  v_content := v_content || E'\n';

  -- 7. #VER + #TRANS — journal entries and lines
  FOR v_entry IN
    SELECT
      je.id,
      je.voucher_series,
      je.voucher_number,
      je.entry_date,
      je.description,
      je.source_event_type
    FROM   journal_entries je
    WHERE  je.organization_id    = p_org_id
      AND  je.financial_period_id = p_period_id
      AND  je.status             = 'posted'
    ORDER  BY je.voucher_series, je.voucher_number
  LOOP
    v_content := v_content
      || '#VER ' || v_entry.voucher_series
      || ' ' || v_entry.voucher_number::text
      || ' ' || TO_CHAR(v_entry.entry_date, 'YYYYMMDD')
      || ' "' || REPLACE(COALESCE(v_entry.source_event_type, v_entry.description), '"', '''') || '"'
      || ' {' || E'\n';

    FOR v_line IN
      SELECT
        account_code,
        -- SIE4 convention: positive = debit, negative = credit
        CASE WHEN debit_amount > 0 THEN debit_amount ELSE -credit_amount END AS amount,
        description,
        entry_id
      FROM   journal_lines
      WHERE  entry_id = v_entry.id
      ORDER  BY line_number
    LOOP
      v_content := v_content
        || '#TRANS ' || v_line.account_code
        || ' {} ' || TO_CHAR(v_line.amount, 'FM999999999990.00')
        || ' ' || TO_CHAR(v_entry.entry_date, 'YYYYMMDD')
        || ' "' || REPLACE(COALESCE(v_line.description, ''), '"', '''') || '"'
        || E'\n';
    END LOOP;

    v_content := v_content || '}' || E'\n' || E'\n';
    v_entry_count := v_entry_count + 1;
  END LOOP;

  -- 8. #UB — closing balances
  FOR v_ub IN
    SELECT account_code, closing_balance
    FROM   account_balances
    WHERE  organization_id    = p_org_id
      AND  financial_period_id = p_period_id
    ORDER  BY account_code
  LOOP
    v_content := v_content
      || '#UB 0 ' || v_ub.account_code
      || ' ' || TO_CHAR(v_ub.closing_balance, 'FM999999999990.00')
      || E'\n';
  END LOOP;

  -- 9. Compute SHA-256 hash
  v_hash := encode(sha256(convert_to(v_content, 'UTF8')), 'hex');

  -- 10. Insert immutable export record
  INSERT INTO ledger_sie4_exports (
    organization_id, financial_period_id,
    from_date, to_date,
    content_text, content_hash,
    entry_count, account_count,
    generated_by
  ) VALUES (
    p_org_id, p_period_id,
    v_period.period_start, v_period.period_end,
    v_content, v_hash,
    v_entry_count, v_account_count,
    p_actor_id
  ) RETURNING id INTO v_export_id;

  -- 11. Emit SIE4.LedgerGenerated event
  PERFORM insert_outbox_event(
    'SIE4.LedgerGenerated',
    'accounting',
    jsonb_build_object(
      'export_id',         v_export_id,
      'period_id',         p_period_id,
      'period_name',       v_period.name,
      'entry_count',       v_entry_count,
      'account_count',     v_account_count,
      'content_hash',      v_hash,
      'generated_by',      p_actor_id
    ),
    p_org_id,
    NULL
  );

  RETURN v_export_id;
END;
$$;

COMMENT ON FUNCTION public.generate_sie4_from_ledger(uuid, uuid, uuid) IS
  'Generates a complete SIE4 file from the journal ledger for a financial period. '
  'Uses journal_entries + journal_lines as authoritative source. '
  '#KPTYP BAS2020, SHA-256 hash for integrity. '
  'Idempotent: returns existing export_id if already generated for this period.';

GRANT EXECUTE ON FUNCTION public.generate_sie4_from_ledger(uuid, uuid, uuid)
  TO authenticated, service_role;
